### ISSUE TITLE
❤️ 欢迎小伙伴们加入微信交流群~ ✿✿ヽ(°▽°)ノ✿

### ISSUE THREAD

**Issue by XPoet** [XPoet/js-data-structure-and-algorithm#6]
欢迎小伙伴们加入前端技术交流群，一起学习~

因群人员大于 200 人，需要扫描下方二维码关注公众号《前端鼓励师》，添加作者微信，再由作者拉你进群~

![FEC-Card](https://cdn.jsdelivr.net/gh/XPoet/image-hosting@master/FE-Cheerleaders/FEC-Card.76dbi8n1bkk0.png)

**Comment by XPoet** [comment]
关于 JavaScript数据结构与算法的任何问题和前端技术问题，都可以在群里提问，作者会积极为大家解答，同时，群里会经常分享学习干货、视频教程、面试指南等，也会经常给大家发红包，欢迎加入~━(*｀∀´*)ノ亻! 🌹🌹🌹

**Comment by ishowman** [comment]
微信群很难形成技术交流的氛围，即使提问也鲜有人回答，信息流也很碎片化。加过几个技术群最后大多走上这样的命运。
